######################################################################
# Automatically generated by qmake (2.00a) Thu Oct 5 17:50:58 2023
######################################################################

TEMPLATE = app
TARGET += 
DEPENDPATH += . src ui
INCLUDEPATH += .

# Modules
QT += gui
QT += network

# Input
FORMS = ui/main.ui
SOURCES = src/ghh_json.c src/json.cpp src/main.cpp src/status.cpp

QMAKE_CFLAGS += -std=c99
